site_name: Molderia Wiki

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
extra_files:
    - docs/CNAME

