# Simple workflow for deploying static content to GitHub Pages
name: Pages Deploy from Marketplace

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN:
          CUSTOM_DOMAIN: molderia.hexhiker.com
          CONFIG_FILE: folder/mkdocs.yml
          EXTRA_PACKAGES: build-base